export const REQUEST_ALL_TICKETS = 'REQUEST_ALL_TICKETS';
export const RECEIVE_ALL_TICKETS = 'RECEIVE_ALL_TICKETS';
export const VIEW_TICKET = 'VIEW_TICKET';

/*AUTHENTICATION ACTION TYPES*/
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const FETCH_USER = 'FETCH_USER';
export const IS_FETCHING_STATUS = 'IS_FETCHING_STATUS';