export const REQUEST_ALL_TICKETS = 'REQUEST_ALL_TICKETS';
export const RECEIVE_ALL_TICKETS = 'RECEIVE_ALL_TICKETS';

/*AUTHENTICATION ACTION TYPES*/
export const USER_LOGIN = 'USER_LOGIN';
export const LOGIN_ERROR = 'LOGIN_ERROR';